### ISSUE TITLE
שינויי seo

### ISSUE THREAD

**Issue by shirachen** [nizanmalkit/bike#100]
1.  לבטל גלילה אינסופית בדפי צפון, דרום, מרכז, כל המסלולים, יש להשאיר גלילה אינסופית רק בעמודי תוצאות חיפוש – אם יש צורך בהסבר טלפוני – דבר איתי

כנ"ל גם באי ירוק

**Comment by naticomstar** [comment]
עודכן באתר אופניים, ויעלה גם באי ירוק לאחר שתסתיים הישיבה שלכם מול קק"ל

**Comment by shirachen** [comment]
אז אחרי שניקיתי קאש...
אלו קצת זזים
![image](https://cloud.githubusercontent.com/assets/14195653/10714477/a287c2bc-7af9-11e5-8b7e-f5e21d021a8d.png)

**Comment by nizanmalkit** [comment]
זה נראה תקין ותואם להנחיות של גוגל. 
רק בעיה אחת - 
במקרה של הדף הראשון (החלק העליון של הדף), נוצרים שני דפים למעשה: 
http://www.eyarok.org.il/bike/trips.aspx
http://www.eyarok.org.il/bike/trips.aspx?page=1 
כשהפרמטר מתווסף לדף במהלך הגלילה. 
צריך להוסיף תגית קנוניקל בדף עם הפרמטר (רק בדף הראשון, page=1?) שתפנה לדף בלי הפרמטר.

**Comment by naticomstar** [comment]
בוצע
