### ISSUE TITLE
תוכן משכופל בגרסראות הדפסה

### ISSUE THREAD

**Issue by shirachen** [nizanmalkit/bike#101]
1.  נוצר תוכן משוכפל בדפי גירסאות ההדפסה. לדוגמא: http://www.eyarok.org.il/bike/print.aspx?id=1968
   ע"מ למנוע את זה, יש להוסיף בכל דפי ההדפסה תגית canonical לדף המקורי. לדוגמא:
   בדף הזה להוסיף: <link href="http://www.eyarok.org.il/bike/trip.aspx?id=1968" rel="canonical" />

**Comment by OmerComstar** [comment]
בוצע
