### ISSUE TITLE
איפה מזינים תמונה ייחודית לעמוד הבית?

### ISSUE THREAD

**Issue by shirachen** [nizanmalkit/bike#103]
![image](https://cloud.githubusercontent.com/assets/14195653/10478341/85f9adc8-7265-11e5-8057-57fe38e6cac4.png)

**Comment by OmerComstar** [comment]
בכל מסלול יש תחת תיקיית "תמונות" סימון של "קבע כתמונת היידר".
סימון של הנ"ל גורם לתמונה שנבחרה להיות התמונה המוצגת בעמוד הבית.

**Comment by shirachen** [comment]
זה לא ההאדר.
אם כבר זה המיין 
במערכת הניהול תחת מונות ניתן לבחור שתי תמונות אחת צרה וארוכה (האדר) 
ואתר מרובעת (מיין)
כרגע המערכת שואבת אל תמונה שתופחיע בעמוד הבית (מסלולים נבחרים) 
את תמונת המיין 
זה לא מה שהתכוונו 
אני רוצה תמונה נוספת לעמוד הבית!
כי המיין היא זו שמוםיע כאראשית במסלול  ואני צריכה עוד אחת

**Comment by naticomstar** [comment]
האם מעוניינת שתישאב התמונה המיוחדת של תחליף אאוטבריין לעמוד הבית במידה וקיימת?

**Comment by shirachen** [comment]
לא. אני רוצה תמונה נוספת כפי שנכתב באפיון
תודה

**Comment by naticomstar** [comment]
נוסף אזור חדש של תמונה ראשית לעמוד הבית של אופניים
![image](https://cloud.githubusercontent.com/assets/13998692/10726891/8b2afff4-7bde-11e5-8ecc-b149325aa6a0.png)
