### ISSUE TITLE
אקטיביזציה של כתבה

### ISSUE THREAD

**Issue by shirachen** [nizanmalkit/bike#105]
אני מנסה לאקטב את הכתבה הזו, אך גם אחרי שאני בוחר להציג אותה ולוחץ על "תצוגה מקדימה של הדף" אני מקבל הודעת שגיאה בזו הלשון:
The page cannot be displayed because an internal server error has occurred.

![image](https://cloud.githubusercontent.com/assets/14195653/10482723/2cea5bc4-7283-11e5-9fca-6275dbce5bf1.png)

**Comment by OmerComstar** [comment]
טופל

**Comment by shirachen** [comment]
לא תקין,

העמוד עכשיו נפתח, אבל לא מופיע בו המלל שמוכנס בתוכן....

**Comment by naticomstar** [comment]
עודכן מקומית, יעלה לאחר סיום הישיבה
