### ISSUE TITLE
התנהגות מוזרה במספרי מסלולים

### ISSUE THREAD

**Issue by shirachen** [nizanmalkit/bike#106]
למשל אם אנחנו נמצאים בעמוד הזה
http://www.eyarok.org.il/bike/trip.aspx?id=1998

ואנחנו משנים רק את ה id 
למשל ל 1950
הוא מעביר אותנו לעמוד מסלול לאי ירוק ולא באופניים או מציג עמוד שגיאה של האופניים.
מדוע?
![image](https://cloud.githubusercontent.com/assets/14195653/10486212/9399556a-7296-11e5-8edb-b9e56e48f580.png)

אם כותבים למשל סתם מספר לא קיים ב id  הוא נותן במקום דף 404 
את העמוד הזה
![image](https://cloud.githubusercontent.com/assets/14195653/10486245/c0eac7ce-7296-11e5-80bd-3dbc4b703d2a.png)

ועוד ניסיון שעשינו כתבנו מספר אחר... אני לא זוכרת לשחזר המספר שהקלדנו  הביא אותי לאירוע שפג תוקפו בכלל של אי ירוק ואפילו לא אופניים

**Comment by OmerComstar** [comment]
אתם לא אמורים לשנות את המספרים ככה, אלו דפים שאתם ממציאים בעצם. בדיוק כמו שאם תרשמו במקום המספר "משה" או כל דבר אחר.
אין לדפים "המומצאים" שלכם קישור משום מקום באתר ולכן אין בעיית SEO.
אנחנו יכולים לגרום לכך שכל טיול יגיע למקום הנכון אם משנים את המספרים ע" חיפוש המספר בכל הוסגים השונים והעברה לסוג שמתאים (עם הפניית 301) - ידרוש 4 שעות.

**Comment by shirachen** [comment]
השאלה היא למה אם אנחנו כותבים URL אשר בעצם לא קיים (מומצא כמו שאתה אומר -משה..) הוא לא מעביר לדף שגיאה (404)? האם כי עוד לא הגדרת? כי כן הגדרת, לא?
כאן: http://www.eyarok.org.il/bike/page.aspx?id=201 

ולמה לפעמים הוא מודיע על סרבר אררור כמו בצילום למעלה?

**Comment by naticomstar** [comment]
חובר עמוד 404 למספרי מסלולים אירועים וכו' שלא קיימים עדיין. בנוסף, מסלול 1950 שייך כנראה לאי ירוק ולכן עברתם לאתר אי ירוק...
