### ISSUE TITLE
לחיצה על תמונה תעביר לעמוד 

### ISSUE THREAD

**Issue by shirachen** [nizanmalkit/bike#107]
בבקשה שלחיצה על התמונה תעביר לעמוד המבוקש
גם  בתוצאות החיפוש עבור כל תוצאה שהיא..
![image](https://cloud.githubusercontent.com/assets/14195653/10488035/8042dea6-729f-11e5-9722-5e6a1bd65337.png)

גם בעמודי אב 
![image](https://cloud.githubusercontent.com/assets/14195653/10488065/a1d76f32-729f-11e5-8228-b5c186177f05.png)

גם בכתבות שטח
![image](https://cloud.githubusercontent.com/assets/14195653/10488114/c7c144c0-729f-11e5-9cd4-b59b73e1b3ca.png)

**Comment by naticomstar** [comment]
ידרוש שעת פיתוח (עבור עמודי החיפוש, עמוד מסלול, עמוד כתבות שטח), נא אישורכם

**Comment by shirachen** [comment]
מאושר

**Comment by naticomstar** [comment]
בוצע ועלה
