### ISSUE TITLE
איפה מזינים פופ אפ לאתר האופניים? 

### ISSUE THREAD

**Issue by shirachen** [nizanmalkit/bike#108]
![image](https://cloud.githubusercontent.com/assets/14195653/10491490/93e57260-72af-11e5-92a0-c0d3082917a3.png)

**Comment by OmerComstar** [comment]
אשמח אם תכווני אותי למוקם בו נמצא הפופ אף בקבצי העיצוב ע"מ לאתר את הפופ אפ המדובר.
