### ISSUE TITLE
החיפוש באתר האופניים 

### ISSUE THREAD

**Issue by shirachen** [nizanmalkit/bike#109]
למה כשכותבים מכתש רמון עולה המסלול הזה?
![image](https://cloud.githubusercontent.com/assets/14195653/10505772/ada0df18-7319-11e5-89bf-15fc043ad469.png)

כי כתוב שם חרמון ?)?))?)?
מה זה הדבר הזה? 
![image](https://cloud.githubusercontent.com/assets/14195653/10505792/dad41108-7319-11e5-99d5-c1c25666d18d.png)

![image](https://cloud.githubusercontent.com/assets/14195653/10505800/eefc735a-7319-11e5-971a-f7967c45962b.png)

![image](https://cloud.githubusercontent.com/assets/14195653/10505816/0cb16c70-731a-11e5-84a1-bb6b33f4974b.png)

**Comment by OmerComstar** [comment]
כן.

לפי דרישות האפיון של חיפוש גם חלק ממילה אמור לתפוס. אם זה לא יהיה כך, חיפוש של "סינגל" לא ימצא תוצאות של "סינגלים" למשל.

**Comment by shirachen** [comment]
אלה לא היו דרישות האיפיון.

**Comment by naticomstar** [comment]
תוקן מקומית, יעלה בעדכון החדש
