### ISSUE TITLE
עמודי אב

### ISSUE THREAD

**Issue by shirachen** [nizanmalkit/bike#11]
אצלי באקפלורר (לפטופ) אין תצוגת פירורים ויש בעיית רווחים והתמונה משתכפלת? קופצת...
![image](https://cloud.githubusercontent.com/assets/14195653/9757514/c88f30fa-56e9-11e5-8dcb-ee2323b52303.png)

אצל איילון בכרום במסכי hd 
![image](https://cloud.githubusercontent.com/assets/14195653/9757547/fa68c8de-56e9-11e5-8838-2d41516de660.png)

**Comment by naticomstar** [comment]
תוקן (לא היה רק באקספלורר) פירורים + תמונה כפולה + נוסף רווח לכותרת הירוקה

**Comment by shirachen** [comment]
היי נתי אצלי באקספלורר אחרי רענון זה נראה ככה 
![image](https://cloud.githubusercontent.com/assets/14195653/9761021/a4019778-5702-11e5-95b9-8c991098b7d7.png)

אצל איילון ככה
![image](https://cloud.githubusercontent.com/assets/14195653/9761037/c96e8fde-5702-11e5-9872-13bc048d6bda.png)

**Comment by naticomstar** [comment]
עודכן פירורי לחם בעמוד מסלול אב
