### ISSUE TITLE
עמוד 404 

### ISSUE THREAD

**Issue by shirachen** [nizanmalkit/bike#110]
היי,
כאמור - עמוד זה נשלט מהניהול אבל הוא לא "מחובר" ברמת האתר, כלומר עמודי שגיאה אינם מציגים את העמוד.
עמר "ניתק" את זה עד שנשנה שם את התמונה - עכשיו ניתן לחבר בחזרה.

זה פה בניהול:
http://www.eyarok.org.il/admin/EditGeneralPage.aspx?type=1&id=201&cat=47&sub=3

תודה

**Comment by naticomstar** [comment]
עודכן

**Comment by shirachen** [comment]
אפשר למרכז את זה לפי סוגי המסכים השונים
למשל ראו בגרסת הדסקטופ אצלי 
![image](https://cloud.githubusercontent.com/assets/14195653/10668334/81b99a72-78e4-11e5-9b14-38d9126c4485.png)

וזה עוד מסך קטן - לא hd

**Comment by naticomstar** [comment]
יש למרכז זאת בעורך הCK

**Comment by shirachen** [comment]
למרות שבמערכת הניהול התמונה ממורכזת, היא מופיעה בצד ימין של העמוד.
![image](https://cloud.githubusercontent.com/assets/14195653/10755096/4b5e4af4-7ca4-11e5-9b67-c8516dc229d2.png)

**Comment by naticomstar** [comment]
טופל (עדכנתי דרך ה
CK)
