### ISSUE TITLE
חדשות חמות

### ISSUE THREAD

**Issue by shirachen** [nizanmalkit/bike#111]
היי נתי 
ניסינו להזין חדשה חמה באתר האופניים - אבל זה לא עובד
זה מה שעשינו בניהול
![image](https://cloud.githubusercontent.com/assets/14195653/10715715/a4fa51e8-7b28-11e5-8068-0911e91ea400.png)

וככה נראה העמוד - וגם יש בעיה עם האייקון מימין 
![image](https://cloud.githubusercontent.com/assets/14195653/10715712/91d7480a-7b28-11e5-93e5-a2001e027f19.png)

**Comment by naticomstar** [comment]
הוסבר כבר בעבר כי הקישור להודעה לא מתבצע מההודעה עצמה אלא מהמסלול עצמו
![image](https://cloud.githubusercontent.com/assets/13998692/10725794/631fab6a-7bd7-11e5-964e-6edd41a98c74.png)

בנוסף אנא נקו קאש, רואים תקין אייקון
![image](https://cloud.githubusercontent.com/assets/13998692/10725802/7467fbca-7bd7-11e5-94a4-17bdee099a8d.png)

**Comment by shirachen** [comment]
תשלח בבקשה צילום מסך איפה מזינים את זה
תודה

![image](https://cloud.githubusercontent.com/assets/14195653/10729487/58dcc3e8-7bf2-11e5-8338-5758809e6a25.png)

**Comment by naticomstar** [comment]
כבר הסברתי זאת מספר פעמים. הודעה חמה מתחלקת ל2:
1. הקמת ההודעה.
2. שיוכה למסלולים.

הקמת ההודעה מתבצעת דרך ניהול ההודעות ב"אפשרויות משותפות" (שימו לב כי "כתובת URL" אינה המקום לשייך בו את המסלול)
![image](https://cloud.githubusercontent.com/assets/13998692/10733491/bf4ee506-7c07-11e5-93e2-c8c0d1d27a0f.png)

שיוך ההודעה למסלול מתבצעת דרך המסלול עצמו, תחת אזור "קישור הודעות" (כך ניתן לשייך כמה הודעות למסלול אחד, ואת אותה הודעה לכמה מסלולים)
![image](https://cloud.githubusercontent.com/assets/13998692/10733504/cee4db38-7c07-11e5-8ca5-bf4e4e3c438c.png)

**Comment by shirachen** [comment]
ניתן להכניס חדשות חמות, אך ישנה בעיה עם התאריך,
בניהול לא ניתן להגדיר את התאריך עצמו אלא רק את התוקף (עד איזה תאריך תוצג ההודעה) 

![image](https://cloud.githubusercontent.com/assets/14195653/10765898/b36165ee-7cdd-11e5-94f7-b2e8fc81d29f.png)

אך בפועל ישנה אינדיקציה על תאריך, שאינה תואמת את התאריך הנכון, היום ה-27 באוקטובר ובאתר רואים 25 באוקטובר.
![image](https://cloud.githubusercontent.com/assets/14195653/10765912/c1f6b870-7cdd-11e5-8c8c-8270b85ba0c7.png)

**Comment by naticomstar** [comment]
התאריך הינו תאריך העלאת ההודעה (מתי יצרו אותה)- עדיף כעיקרון לגולש לדעת ממתי ההודעה עדכנית מאשר סתם תאריך של היום
(במקור לא אופיין)

**Comment by shirachen** [comment]
ממש לא נכון
בבקשה תחזור לאיפון של אתר האופניים באקסל הענק ותראה 
![image](https://cloud.githubusercontent.com/assets/14195653/10904427/aed7320e-821b-11e5-89f7-8cf014ce9cc2.png)

**Comment by naticomstar** [comment]
עודכן באתר האופניים
