### ISSUE TITLE
נעלמו מגוגל דפי המסלולים האיזוריים באתר האופניים

### ISSUE THREAD

**Issue by nizanmalkit** [nizanmalkit/bike#115]
הבוקר נעלמו מגוגל דפי המסלולים האיזוריים באתר האופניים (מסלולי צפון, מסלולי מרכז ומסלולי דרום). 
בדקנו ומצאנו שבוצע איזשהו שינוי בקוד של העמודים, ונוספה להם הפניית קנוניקל לדף כל המסלולים : 

<link id="CanonicalURL" rel="canonical" href="http://www.eyarok.org.il/bike/trips.aspx" />

צריך להוריד את ההפנייה הזו בהקדם, מפני שהיא מפריעה לגוגל לאנדקס את העמודים ולכן הדירוגים מושפעים לרעה. 

אלו העמודים שיש לתקן:
http://www.eyarok.org.il/bike/trips.aspx?filter=north
http://www.eyarok.org.il/bike/trips.aspx?filter=center
http://www.eyarok.org.il/bike/trips.aspx?filter=south

**Comment by naticomstar** [comment]
תוקן.
נבע מהתוספת האחרונה של הגלילה האינסופית שגרם לכך שהקנוניקל לא יעבוד. הקנוניקל תוקן באותו רגע אך לא נלקח מקרה קצה של פילטרים בעמוד החיפוש.
נוסף כרגע בעמוד החיפוש לקיחה בחשבון בנוגע לפילטרים
