### ISSUE TITLE
חיבור לפייסבוק

### ISSUE THREAD

**Issue by shirachen** [nizanmalkit/bike#116]
היי,

כשאני מפרסם פוסט ובו קישור לאתר האופניים, נשאבת תמונה של אי ירוק (מאחר ואנחנו מסונפים לדומיין שלהם).
זה כמובן לא טוב לנו...
הייתי רוצה שכשנשתלים קישורים לאתר האופניים התמונה שתשאב תהיה הלוגו של האתר (מצורף)

ככה זה נראה עכשיו:
![image](https://cloud.githubusercontent.com/assets/14195653/10931788/6a886880-82d3-11e5-9694-08803f29f91f.png)

**Comment by naticomstar** [comment]
ידרוש שעת פיתוח ואת התמונה עצמה, נא אישורכם

**Comment by shirachen** [comment]
מאושר.
איזה תמונה להעביר?
מה המידות? יש עדיפות לפורמט כזה או אחר?

**Comment by naticomstar** [comment]
תמונה בגודל 300 על 300
עדיפות ל
JPG,
שלא יחרוג מגודל 300 קילובייט

**Comment by naticomstar** [comment]
![image](https://cloud.githubusercontent.com/assets/13998692/11086541/d4f5c3de-885a-11e5-8f55-4ae175e27bd4.png)

**Comment by shirachen** [comment]
תודה 
![image](https://cloud.githubusercontent.com/assets/14195653/11087566/072f2e5e-8864-11e5-92eb-04510f9e059b.png)

**Comment by naticomstar** [comment]
שלחי לי את הלינק של העמוד שאותו את מנסה לשתף
