### ISSUE TITLE
אירוע שחלף בחיפוש

### ISSUE THREAD

**Issue by shirachen** [nizanmalkit/bike#117]
כאשר ביצענו חיפוש אחר "אופקים"  
התוצאה שקיבלנו מועיה בצילום יש כאן 2 בעיות
- ראו שהלינק של האירוע מוביל לעמוד לא קיים
- והוא בכלל אמור להוביל לאירוע הקיים באתר - זה שחלף לו
  http://www.eyarok.org.il/bike/event.aspx?d=30-09-2015

![image](https://cloud.githubusercontent.com/assets/14195653/11095293/02ffeff6-889d-11e5-8c7e-99cfb76fbe74.png)

**Comment by naticomstar** [comment]
תוקן
