### ISSUE TITLE
הודעת שגיאה להוריד מפות מדפי מסלול במובייל אצל לקוחה

### ISSUE THREAD

**Issue by kazantip151** [nizanmalkit/bike#119]
היי.
ללקוחה יש בעיה להוריד מפות במובייל.
יש לה SAMSUNG GALAXY 3.

![error](https://cloud.githubusercontent.com/assets/2787866/11236184/3743c9b6-8de0-11e5-9c7e-693325a6fb70.jpg)

**Comment by naticomstar** [comment]
ניסיתי לחפש את שם הקובץ הזה במסד הנתונים אך אני רואה שהוא לא קיים. אבקש לדעת באיזה מסלול מדובר כדי שוכל לחקור את העניין

**Comment by kazantip151** [comment]
זה היה בשביל קנים.

**Comment by naticomstar** [comment]
בדקתי מסלול זה,
שני הקבצים שנמצאים שם תקינים. לדעתי היה קובץ שהחליפו אותו והיא ניסתה להוריד אותו שוב (לא ריעננה עמוד או משהו דומה)
