### ISSUE TITLE
שכפול עמוד של אתר אופניים גם באי ירוק

### ISSUE THREAD

**Issue by kazantip151** [nizanmalkit/bike#120]
היי.
כתבת "10 כלים ש.." שעלתה באתר האופניים מופיעה משום מה גם באי ירוק
הקישור של הכתבה באתר האופניים הוא: http://www.eyarok.org.il/bike/article.aspx?id=1973
הקישור לכתבה באי ירוק הוא: http://www.eyarok.org.il/article.aspx?id=1973&cmt=4877

מעבר לעובדה שזה יוצר לנו בעיה SCO, לא ברור לי מאיפה נולד התאום הזה...

**Comment by naticomstar** [comment]
נוסף קוד בעמוד כתבות המגזין שאם מדובר באתר אופניים, יבצע הפניה.
