### ISSUE TITLE
כפתור הדפס בכל עמוד מסלול לא עובד

### ISSUE THREAD

**Issue by kazantip151** [nizanmalkit/bike#121]
היי.
הכפתור הדפס לא עובד בשום עמוד מסלול, וגם פותח טאב נפרד עם עמוד שלא קיים.

![print](https://cloud.githubusercontent.com/assets/2787866/11239451/c434ce2e-8df4-11e5-99f0-00c33231a8c0.JPG)
עמוד שגיאה:

![error2](https://cloud.githubusercontent.com/assets/2787866/11239463/d08dd4ae-8df4-11e5-860e-8afd9241d066.JPG)

**Comment by naticomstar** [comment]
תוקן
(ctrl + F5)
