### ISSUE TITLE
הרשמה לניוזלטר אופניים מעקב הרשמה

### ISSUE THREAD

**Issue by kazantip151** [nizanmalkit/bike#123]
היי,
בדף הבית יש שני מקומות בה אפשר להירשם לאתר האופניים
1.  האם אפשר לדעת לפי פרמטר או משהו כמה נרשמו דרך החלוניות המהירות האלו?
2.  אני רוצה שבלחיצה על "הרשמה לניוזלטר" יפתח דף ההרשמה עם פרמטר נוסף שאעביר לכם... אפשר? אם כן אנא עדכנו שם את הלינק הזה:
http://www.eyarok.org.il/bike/contact.aspx?source=klik_footer_28778
וככה אני אראה את זה גם אחרי שהם נרשמו, נכון? 
תודה 

![arshama](https://cloud.githubusercontent.com/assets/2787866/11418201/8321143c-9426-11e5-9151-b95109d5aea3.jpg)

**Comment by naticomstar** [comment]
היי אלכס,

א. כרגע לא ניתן להבחין בטופס בין 2 מקומות ההרשמה (אלא אם כן אתה מחפש כאלה שמילאו רק שם ומייל מול אלה שמילאו את כל הפרטים.
ניתן יהיה להוסיף "source" לרישום מהניוזלטר שנמצא למטה (חבוי) כך שתוכלו לראות שהוא הגיע משם
ב. ניתן להוסיף פרמטר ללינק של "הרשמה לניוזלטר" כפי שביקשת.

כל הנ"ל יעלה 1 שעות עבודה.

**Comment by kazantip151** [comment]
מאושר
עדכנו כשבוצע
וגם איזה פרמטר אתם שמים...

**Comment by naticomstar** [comment]
יעלה עדכון יחד עם השינוי ברישום לניוזלטרים
