### ISSUE TITLE
עמוד ארכיון הניוזלטרים לא  מותאם מובייל

### ISSUE THREAD

**Issue by kazantip151** [nizanmalkit/bike#124]
היי זה נראה כאילו לא ביצעו את העמוד הזה מותאם מובייל
אנא טיפולכם
תודה 

זה העמוד
http://www.eyarok.org.il//bike/newsletterarchive.aspx

וככה זה נראה בטלפון שלי (אייפון 6s)
![mob](https://cloud.githubusercontent.com/assets/2787866/11418236/d747042c-9426-11e5-9248-92a88ca0e25c.jpg)

**Comment by naticomstar** [comment]
תוקן
