### ISSUE TITLE
אי אפשר להגיב באתר

### ISSUE THREAD

**Issue by kazantip151** [nizanmalkit/bike#125]
אי אפשר להגיב באתר, לא משנה כמה פעמים ריעננתי, העתקתי את הטקסט לכתבן, קיצרתי ומה לא, הוא לא מקבל את התגובה.
![comments](https://cloud.githubusercontent.com/assets/2787866/11418459/939ed0d6-9428-11e5-9a0f-d18f590a6c0b.png)

**Comment by naticomstar** [comment]
היי

הצלחתי הרגע
![image](https://cloud.githubusercontent.com/assets/13998692/11418584/c9b31b36-9429-11e5-8bfd-1f891bd950bc.png)

באיזה מסלול מדובר?

**Comment by kazantip151** [comment]
מדובר במסלול הזה:
http://www.eyarok.org.il/bike/article.aspx?id=2057
אבל צריך לבדוק שזה עובד בכל המסלולים.

**Comment by naticomstar** [comment]
יעלה תיקון יחד עם השינוי ברישום לניוזלטרים
