### ISSUE TITLE
דף הבית אקפלורר 10 לפטופ

### ISSUE THREAD

**Issue by shirachen** [nizanmalkit/bike#14]
בדף הבית זה קופץ... כבר הערתי את זה בעבר

![image](https://cloud.githubusercontent.com/assets/14195653/9757603/59fac87e-56ea-11e5-85d0-1df3db101e81.png)

**Comment by naticomstar** [comment]
כעת תקין
![image](https://cloud.githubusercontent.com/assets/13998692/9760592/05f4986c-56ff-11e5-817c-dcedd4c94c11.png)

**Comment by shirachen** [comment]
עדיין לא תקין באקפלורר 10 מסך לפטופ

**Comment by naticomstar** [comment]
כעת תקין
