### ISSUE TITLE
כפתורים בעמוד מסלול שיתוף הדפסה וכו אקספלורר 10 לפטופ

### ISSUE THREAD

**Issue by shirachen** [nizanmalkit/bike#15]
![image](https://cloud.githubusercontent.com/assets/14195653/9757629/767675de-56ea-11e5-9989-f280657862ae.png)

![image](https://cloud.githubusercontent.com/assets/14195653/9757641/84904226-56ea-11e5-90ca-074bc9ee1e87.png)

**Comment by naticomstar** [comment]
לבנתיים סגור, נראה תקין

**Comment by shirachen** [comment]
עדיין לא תקין אחרי ניקוי קאש ורענון באקסםלורר 10 מסך לפטופ

**Comment by naticomstar** [comment]
תודה לאל תוקן
