### ISSUE TITLE
תוסף דמוי אווטברין 

### ISSUE THREAD

**Issue by shirachen** [nizanmalkit/bike#16]
![image](https://cloud.githubusercontent.com/assets/14195653/9757660/a0629990-56ea-11e5-857e-bc2db34081a4.png)

**Comment by naticomstar** [comment]
בעמוד מסלול תוקן

**Comment by naticomstar** [comment]
תוקן גם בעמוד כתבות שטח (כרגע יש לכם רק 2 כתבות אחרות ולכן יש לכם "חור" באמצע

**Comment by shirachen** [comment]
לחיצה על כתבת שטח מעבירה לעמוד שגיאה
וגם חסר את הכותרת...  של כתבות השטח...
![image](https://cloud.githubusercontent.com/assets/14195653/9808716/611c3cba-586a-11e5-8953-248cbc3c6a98.png)

**Comment by naticomstar** [comment]
תוקן

**Comment by shirachen** [comment]
חיים של בנק,
הלינק תוקן.אין כותרת "עוד כתבות שטח"
יש  לך גישה לעיצובים?

**Comment by naticomstar** [comment]
הבנק סידר.
(ד"א, כתוב שם "עוד על רכיבת אופניים")

**Comment by shirachen** [comment]
תודה וגם עוד דבר

והכפתור מימין צריך להיות צבוע בכתום "מואר"
![image](https://cloud.githubusercontent.com/assets/14195653/9811350/4691d16a-587f-11e5-8a7d-d360bbe10240.png)

**Comment by shirachen** [comment]
נתי חיים שלי זה עדיין לא סודר...
![image](https://cloud.githubusercontent.com/assets/14195653/9836271/752f09e6-5a1b-11e5-9c46-15e30ead1adb.png)

צריך להיות מואר מודגש בכתום כמו כל האחרים כשלוחצים עליהם

**Comment by naticomstar** [comment]
צודקת
עכשיו תקין
