### ISSUE TITLE
 ואקספלורר מפות גוגל במסלולים כרום 

### ISSUE THREAD

**Issue by shirachen** [nizanmalkit/bike#19]
זה פותח  את המפה ברזולוציה רחוקה  מאוד והנוקדה היא פיצית פיצית
![image](https://cloud.githubusercontent.com/assets/14195653/9758398/0f9d8f6e-56ef-11e5-9e0d-48da446c94d8.png)

**Comment by shirachen** [comment]
אני מבינה יש שתי דקירות בכל המסלולים אחת קבועה בין ם וזה מרחיק את התצוגה... מאיפה הנקודה ביום באה? 
![image](https://cloud.githubusercontent.com/assets/14195653/9758603/54e2a428-56f0-11e5-91b8-29716f8557fc.png)

**Comment by naticomstar** [comment]
המפה מקבלת זום כזה כיוון שיש לכם נקודת 0,0 בקובץ ה
KML
שעלה במערכת. מזכיר לניצן שהאפשרות הטובה ביותר (לדעתי) היא לבטל את המניפולציה של קבצים אלו באתר עצמו אלא לתכנן הכל ב
google earth
ושנעלה את הקובץ "איך שהוא" לאתר לאחר שסיימתם לעבוד עליו בתוכנה.
כל הכלים כבר שם.

**Comment by nizanmalkit** [comment]
קדימה, בוא נעשה בדיקה.
להבנתי לא תהינה לזה השלכות על כל מה שכבר עלה, נכון?

**Comment by naticomstar** [comment]
נכון. הועלה שינוי במערכת הניהול. יותר לא צריך להיכנס דרך הלינק בהמשך הניהול אל העלאת קובץ זה, אלא העלאת הקובץ מפיעה ישירות בתוך טאב של מפות, ובוטלה המניפולציה של הקבצים.
![image](https://cloud.githubusercontent.com/assets/13998692/9794409/91860d08-57f3-11e5-83c4-72773e42467a.png)

**Comment by shirachen** [comment]
זה אומר שאיילון צריך להזין רק קובץ kml מההחלה למסלולים ואז נראה את התיקון?
הכוונה היא שצריך להזין בכל המסלולים קובצי kml בטאב מפות ולא בלינק המיוחד.
גם לכאלו שכבר העלינו. אמת? אם כן - אתפעל את איילון

**Comment by naticomstar** [comment]
דיברנו טלפונית, איילון יודע מה צריך לבצע
