### ISSUE TITLE
גדלים יישורים וכו'

### ISSUE THREAD

**Issue by nizanmalkit** [nizanmalkit/bike#2]
000נבדק בלפטופ
1366X768 רזולוציה

![image](https://cloud.githubusercontent.com/assets/12142243/9563783/226f4858-4e98-11e5-9732-77d972604f64.png)

![image](https://cloud.githubusercontent.com/assets/12142243/9563792/669a6dd2-4e98-11e5-91db-bafb070fc25a.png)

![image](https://cloud.githubusercontent.com/assets/12142243/9563797/981d94c4-4e98-11e5-864b-cf44150f746a.png)

![image](https://cloud.githubusercontent.com/assets/12142243/9563800/c26d2bea-4e98-11e5-8fcb-36d0a23492d4.png)

![image](https://cloud.githubusercontent.com/assets/12142243/9563815/aad2df1a-4e99-11e5-869e-ff433fab58f8.png)

![image](https://cloud.githubusercontent.com/assets/12142243/9563824/41e7a0de-4e9a-11e5-9081-8dfaec939259.png)

![image](https://cloud.githubusercontent.com/assets/12142243/9563838/c107deec-4e9a-11e5-8745-871eaed90bba.png)

![image](https://cloud.githubusercontent.com/assets/12142243/9563850/4b9fa418-4e9b-11e5-8e39-38cdf5590f64.png)

![image](https://cloud.githubusercontent.com/assets/12142243/9563855/7bc99374-4e9b-11e5-97c5-382d24fa7d83.png)

![image](https://cloud.githubusercontent.com/assets/12142243/9563899/6b9636f0-4e9c-11e5-847d-838694d2bd6c.png)

![image](https://cloud.githubusercontent.com/assets/12142243/9563927/5dbc386c-4e9d-11e5-8cb6-3d2246c81c8c.png)

![image](https://cloud.githubusercontent.com/assets/12142243/9563940/bc080400-4e9d-11e5-8916-81e6a8e748ec.png)

**Comment by naticomstar** [comment]
נסיון נסיון 123

**Comment by nizanmalkit** [comment]
יפה
