### ISSUE TITLE
תוצאות חיפוש מתקדם כרום

### ISSUE THREAD

**Issue by shirachen** [nizanmalkit/bike#20]
![image](https://cloud.githubusercontent.com/assets/14195653/9758842/a44c0b5c-56f1-11e5-8d84-ea86a54951a8.png)

**Comment by naticomstar** [comment]
כעת תקין. בכל מקרה זאת לא התצוגה של "אין תשובות", היתה בעיה בשאילתא שכן בבוקר החזרנו את המרחקים לעיצוב הראשוני

**Comment by shirachen** [comment]
כחלק מכל ההערות על החיפוש... זה עדיין לא בסדר.

**Comment by naticomstar** [comment]
תקין

**Comment by shirachen** [comment]
יופי תודה
