### ISSUE TITLE
עמוד תגית 

### ISSUE THREAD

**Issue by shirachen** [nizanmalkit/bike#22]
איך ומה לעשות כדי לשפר את האייקון שנשאב לכאן?
בעבר אמרת לי לסגור אותם גדול יותר ולהזין בניהול באייקונים - אבל זה הניב תוצאות גרועות יותר... 

![image](https://cloud.githubusercontent.com/assets/14195653/9759045/196b36a0-56f3-11e5-8d58-165e70553a9b.png)

**Comment by naticomstar** [comment]
נא לנסות להעלות שוב את התמונה, היתה הגבלה גם מהצד שלנו והעליתי אותה בהתאם

**Comment by shirachen** [comment]
זה לא עובד העלינו שוב אייקון חדש למשל אייקון של מסלול מעגלי 
300*300 כי שאמרת לנו בעבר  גודל האייקון החדש שהעלינו

![image](https://cloud.githubusercontent.com/assets/14195653/9764848/ea56b016-5719-11e5-9985-acf90598e7c8.png)

**Comment by naticomstar** [comment]
תקין. נא אישורך לחיוב דקת עבודה ;-)
