### ISSUE TITLE
?איפה מזינים מסלולים פופולרים

### ISSUE THREAD

**Issue by shirachen** [nizanmalkit/bike#23]
חיפשתי בניהול... מזכירה לך שיהיו בעתיד גם לאי ירוק כאלו וצריך הפרדה בין אי ירוק לאופניים
![image](https://cloud.githubusercontent.com/assets/14195653/9759209/2339ae86-56f4-11e5-8f35-355f1fbb59dd.png)

וגם יש לכל איזור צפון דרום ומרכז פופלארים...
![image](https://cloud.githubusercontent.com/assets/14195653/9759221/3c930fda-56f4-11e5-960f-1760261d38ad.png)

**Comment by naticomstar** [comment]
![image](https://cloud.githubusercontent.com/assets/13998692/9760293/73b14c40-56fc-11e5-8ad2-f8689c7f7359.png)

**Comment by shirachen** [comment]
במומלצים מרכז ודרום - אין אפשרות לשמור את המסלולים הוא מסמן וי ומנסה לשמור את הבחירה - אבל זה לא נשמר

**Comment by naticomstar** [comment]
עודכן. כעת תקין
