### ISSUE TITLE
עריכת תמונה של גולשים

### ISSUE THREAD

**Issue by shirachen** [nizanmalkit/bike#24]
העליתי תמוה - ואז רציתי לערוך אותה ... 
זה לא פתח לי מחדש את כפתור ה "שלח" 
![image](https://cloud.githubusercontent.com/assets/14195653/9759489/1908e042-56f6-11e5-947c-2fd7e13369d5.png)

וגם לא ראיתי את הטקסט מוצג על התמונה
![image](https://cloud.githubusercontent.com/assets/14195653/9759517/43a9fb6a-56f6-11e5-9c5e-bee96eac402d.png)

**Comment by naticomstar** [comment]
כפתור "שלח" תקין כעת + קסט מתעדכן ללא צורך לרענן את הדף

**Comment by shirachen** [comment]
עשיתי טסט בסובב שקמה 
ככה הזנתי את התמונה בהתחלה
![image](https://cloud.githubusercontent.com/assets/14195653/9761388/22fb7d80-5705-11e5-93a0-023dbb3316a9.png)

וככה זה הציג אותה
![image](https://cloud.githubusercontent.com/assets/14195653/9761405/3b0c1894-5705-11e5-8c48-103ffa4e36a8.png)

חסר הטקסט שכתבתי

**Comment by shirachen** [comment]
לתמונה רק אח"כ בעריכה זה הכניס את הטקסט שלי
![image](https://cloud.githubusercontent.com/assets/14195653/9761479/a5360068-5705-11e5-8d58-63f2ac4092a2.png)

**Comment by naticomstar** [comment]
סודר (העלאת תמונה חדשה,עריכה היה כבר תקין)
