### ISSUE TITLE
 דרך פייסבוק שיתוף המסלול 

### ISSUE THREAD

**Issue by shirachen** [nizanmalkit/bike#25]
![image](https://cloud.githubusercontent.com/assets/14195653/9763377/eb3be814-5711-11e5-9747-d303d473fbcf.png)

אפשר לשלוט במה שמופיע בשיתוף? אם כן מה להבעיר לך? טקסט? תמונה?
![image](https://cloud.githubusercontent.com/assets/14195653/9763437/285192b2-5712-11e5-9dc1-7b3b3ea1b2f1.png)

**Comment by shirachen** [comment]
![image](https://cloud.githubusercontent.com/assets/14195653/9763459/45716d40-5712-11e5-83d2-b8eb1c9d00d6.png)

**Comment by naticomstar** [comment]
בעיקרון הפייסבוק מושך פרטים לבד, הוא נתן לך את הפרטים הכלליים ההם כיוון שיש עדיין סיסמא לאתר
![image](https://cloud.githubusercontent.com/assets/13998692/9808692/35401ff8-586a-11e5-8a68-f3e8eb79efd8.png)

**Comment by shirachen** [comment]
מהרס, תודה
