### ISSUE TITLE
גלריית התמונות כרום 

### ISSUE THREAD

**Issue by shirachen** [nizanmalkit/bike#26]
![image](https://cloud.githubusercontent.com/assets/14195653/9763607/2c97b1fc-5713-11e5-9f49-17bd300a094a.png)

**Comment by naticomstar** [comment]
באיזה מסלול מדובר?

**Comment by shirachen** [comment]
סינגל הרצל הכחול ביער בן שמן

**Comment by naticomstar** [comment]
נבע מתמונה שהיתה חסרה. מחקתי אותה וכעת תקין
