### ISSUE TITLE
העלאת תמונה - ללא התחברות לאתר

### ISSUE THREAD

**Issue by shirachen** [nizanmalkit/bike#27]
זה נתן לי להעלות מבלי להיות מחוברת...
יש לזה פופ אפ שמחייב הרשמה. איפה הוא?
![image](https://cloud.githubusercontent.com/assets/14195653/9763767/f5150c2e-5713-11e5-951a-1ca48bbba211.png)

**Comment by naticomstar** [comment]
עודכן
