### ISSUE TITLE
תזוזת מסלולים בדף הבית

### ISSUE THREAD

**Issue by shirachen** [nizanmalkit/bike#28]
![image](https://cloud.githubusercontent.com/assets/14195653/9763894/b0ac87dc-5714-11e5-9df0-f3f224921a44.png)

![image](https://cloud.githubusercontent.com/assets/14195653/9763922/d9713488-5714-11e5-813a-edf06a8fb639.png)

**Comment by naticomstar** [comment]
cumg

**Comment by naticomstar** [comment]
בוצע
