### ISSUE TITLE
טקסט לאייקונים בחיפוש במסכי לפטופ

### ISSUE THREAD

**Issue by shirachen** [nizanmalkit/bike#3]
![image](https://cloud.githubusercontent.com/assets/14195653/9757250/12fdf060-56e8-11e5-8b4d-5ece5a07adf1.png)

**Comment by naticomstar** [comment]
נוסף הטקסט בלפטופ, הוסר הטקסט בלפטופ וסודר האזור.

**Comment by shirachen** [comment]
תודה  ראה תצוגה באקספלורר 
![image](https://cloud.githubusercontent.com/assets/14195653/9758719/0d2e2b74-56f1-11e5-9c41-185119080f69.png)

**Comment by naticomstar** [comment]
כעת תקין
