### ISSUE TITLE
אייקון צור קשר 

### ISSUE THREAD

**Issue by shirachen** [nizanmalkit/bike#30]
ראה תקלה שאיילון מצא
![image](https://cloud.githubusercontent.com/assets/14195653/9780898/0180e02c-5797-11e5-8856-1f0827e2efdb.png)

**Comment by shirachen** [comment]
כנל גם כאן 
![image](https://cloud.githubusercontent.com/assets/14195653/9783414/c989e4aa-57ac-11e5-8ff5-ac59e0e4490f.png)

**Comment by naticomstar** [comment]
הקוד מוגדר תקין. אם התוכנות אצל הלקוח לא מוגדרות להפעלת תוכנת אימייל כאשר לוחצים על קישור מייל, אין ביכולתנו לעשות כלום בנדון. יש לציין שהנ"ל יקרה בכל אתר בעולם ולא רק באתר זה.
