### ISSUE TITLE
לינקים בעייתים בפוטר

### ISSUE THREAD

**Issue by shirachen** [nizanmalkit/bike#31]
![image](https://cloud.githubusercontent.com/assets/14195653/9780949/98e16b44-5797-11e5-966a-115a1898e81f.png)

**Comment by naticomstar** [comment]
עלה עדכון לניהול הפוטר, ניתן לשלוט האם נפתח בעמוד חדש או לא. חשוב לזכור לנקות רשימות סטטיות בשביל לראות את השינוי
