### ISSUE TITLE
תצוגת מסלול על גבי מפה

### ISSUE THREAD

**Issue by shirachen** [nizanmalkit/bike#33]
![image](https://cloud.githubusercontent.com/assets/14195653/9780994/139f6840-5798-11e5-9736-235ffc24ffeb.png)

**Comment by naticomstar** [comment]
עודכן

**Comment by shirachen** [comment]
מממ אצלי במחשב בבית - זה מציג לי רק מסלול אחד על גבי המפה 
 על גבי רשימה זה מציג בכל... ואני כמובן לחוצה על כל המסלולים כל האיזורים וכו
ויש רק נקודה אחת אדומה. כאילו רק טיול אחד. 
ולחיצה עליו כלל לא מגיבה ולא פותחת כלום
![image](https://cloud.githubusercontent.com/assets/14195653/9810644/db64fdc6-587a-11e5-9621-26b91e2fbb16.png)

**Comment by naticomstar** [comment]
תקני קאש, בדיוק עדכנתי את הנושא
