### ISSUE TITLE
חיפוש מתקדם - אורך מסלול בקילומטרים

### ISSUE THREAD

**Issue by shirachen** [nizanmalkit/bike#34]
![image](https://cloud.githubusercontent.com/assets/14195653/9781017/441c2044-5798-11e5-97a0-e2e73b4b457e.png)

![image](https://cloud.githubusercontent.com/assets/14195653/9781021/67e88c92-5798-11e5-9a5a-1be3d3c9d08b.png)

**Comment by shirachen** [comment]
כמו כן גם חיפוש לפי עונה
![image](https://cloud.githubusercontent.com/assets/14195653/9781284/412cab94-579b-11e5-865c-052f8486d2ea.png)

**Comment by shirachen** [comment]
ועוד תקלה באותו עניין 
סימנו ככה בחיפוש המתקדם 
![image](https://cloud.githubusercontent.com/assets/14195653/9781329/b3291476-579b-11e5-9f67-84479e2c1170.png)

וזה לא מניב תוצאות - אבל קיים מסלול כזה
![image](https://cloud.githubusercontent.com/assets/14195653/9781340/cb5e9a52-579b-11e5-8c7c-9f06397725b1.png)

**Comment by naticomstar** [comment]
עודכן חיפוש לפי מסלול, לפי עונות ולפי תגיות
