### ISSUE TITLE
גלילה בטאב מפות pdf

### ISSUE THREAD

**Issue by shirachen** [nizanmalkit/bike#37]
![image](https://cloud.githubusercontent.com/assets/14195653/9783335/37f0fbf0-57ac-11e5-81e2-94d334906cde.png)

וגם חסר את אלו מהעיצוב
![image](https://cloud.githubusercontent.com/assets/14195653/9783351/5e8ab116-57ac-11e5-892c-7c378d1b9962.png)

**Comment by naticomstar** [comment]
גלילה ואפשרויות השייכות לדפדפן ותצוגת ה
PDF 
בתוכות. אין לנו שליטה עליו (הגלילה נובעת מגודל הקובץ ואין לנו שליטה על זה)
