### ISSUE TITLE
כתבת שטח באקספלורר 10 לפטופ

### ISSUE THREAD

**Issue by shirachen** [nizanmalkit/bike#40]
תצוגת הכתבה באקסלורר 10 קופצת 
![image](https://cloud.githubusercontent.com/assets/14195653/9784037/4b80850a-57b1-11e5-9ce6-716c8014a78a.png)

**Comment by naticomstar** [comment]
נראה תקין כעת.
![image](https://cloud.githubusercontent.com/assets/13998692/9811116/e458475a-587d-11e5-9d14-5f9a7f757b6a.png)
