### ISSUE TITLE
הזנו מסלולים מומלצים!

### ISSUE THREAD

**Issue by shirachen** [nizanmalkit/bike#41]

**Comment by shirachen** [comment]
באקסלורר 11 במסכי לפטופככה זה נראה
![image](https://cloud.githubusercontent.com/assets/14195653/9784387/82d61c8e-57b3-11e5-984f-8db4889a24c4.png)

**Comment by shirachen** [comment]
באקספלורר 10 זה נראה ככה מסך לפטופ
![image](https://cloud.githubusercontent.com/assets/14195653/9785246/8b31b19e-57b9-11e5-83b9-903bb692dbf0.png)

**Comment by naticomstar** [comment]
נראה תקין כעת

**Comment by shirachen** [comment]
אין אפשרות להזין מסלולי אב... 
אנא טיפולך 
תודה

**Comment by naticomstar** [comment]
לא הוגדר באיפיון להגדיר מסלול אב. חוזר ואומר שמסלול אב הוא לא מסלול אמיתי ולכן גם לא הגיוני לשים אותו שם
