### ISSUE TITLE
עדכון טקסט בהתחברות

### ISSUE THREAD

**Issue by shirachen** [nizanmalkit/bike#43]
זה נמה שעולה באתר האופניים
![image](https://cloud.githubusercontent.com/assets/14195653/9787893/25fc8612-57cf-11e5-8e74-71197043d23e.png)

וזה מה שצריל להיות כתוב
![image](https://cloud.githubusercontent.com/assets/14195653/9787920/4a12dd08-57cf-11e5-866f-14d4a5a7f135.png)

**Comment by naticomstar** [comment]
עודכן
