### ISSUE TITLE
צילומי מסך מנקסוס 5 דפדפן כרום

### ISSUE THREAD

**Issue by shirachen** [nizanmalkit/bike#44]
![image](https://cloud.githubusercontent.com/assets/14195653/9788332/afde430a-57d1-11e5-8f3a-1e3efda71189.png)

יש פה פס מיותר
![image](https://cloud.githubusercontent.com/assets/14195653/9788350/cc3ee2fc-57d1-11e5-87f7-f028a6407bf8.png)

כל החלק הזה לא מגיב
![image](https://cloud.githubusercontent.com/assets/14195653/9788360/e0ea7c66-57d1-11e5-8982-74f43d393b28.png)

**Comment by naticomstar** [comment]
תקין
