### ISSUE TITLE
צילומי מסך ממכשיר - xperia z3 דפדפן כרום

### ISSUE THREAD

**Issue by shirachen** [nizanmalkit/bike#45]
זה ברח.. בעיצוב הוא בצד שמאל 
אילון עדיין לא רואה תקין בדק אף באינקוגניטו
![image](https://cloud.githubusercontent.com/assets/14195653/9788394/1efea61c-57d2-11e5-9895-7121724ac5c8.png)
![image](https://cloud.githubusercontent.com/assets/14195653/9788407/36e7664c-57d2-11e5-9e86-4dd4bec672b8.png)

לחיצה על תמונת המסלול הובילה לעמוד הזה
![image](https://cloud.githubusercontent.com/assets/14195653/9788425/622ddb38-57d2-11e5-8835-38afac356d70.png)

שורות נחתכות וגם פס אורכי מיותר
![image](https://cloud.githubusercontent.com/assets/14195653/9788444/84fd766e-57d2-11e5-8322-724d994305f1.png)

![image](https://cloud.githubusercontent.com/assets/14195653/9788455/9e95e1ec-57d2-11e5-8623-248a24b743dc.png)

עמוד מסלול הכל קופץ
![image](https://cloud.githubusercontent.com/assets/14195653/9788468/b2198ea8-57d2-11e5-94ac-e8e292b4e32c.png)

חיפוש יש פס מיותר
![image](https://cloud.githubusercontent.com/assets/14195653/9788478/c8cc73fe-57d2-11e5-8af5-4fe74d1a0615.png)

**Comment by naticomstar** [comment]
עודכן.

**Comment by shirachen** [comment]
ברח.. בעיצוב הוא בצד שמאל 
אילון עדיין לא רואה תקין בדק אף באינקוגניטו
![image](https://cloud.githubusercontent.com/assets/14195653/9788394/1efea61c-57d2-11e5-9895-7121724ac5c8.png)

עדיין האייקונים קופצים אצלו...
מוד מסלול הכל קופץע
![image](https://cloud.githubusercontent.com/assets/14195653/9788468/b2198ea8-57d2-11e5-94ac-e8e292b4e32c.png)

**Comment by naticomstar** [comment]
כעת תקין יותר
