### ISSUE TITLE
 מיקום טאג  מנג'ר

### ISSUE THREAD

**Issue by nizanmalkit** [nizanmalkit/bike#46]
הקוד של תג מנג׳ר באתר האופניים ממוקם כרגע אחרי תגית <head> ,
צריך להעביר אותו למיקום מיד אחרי תגית <body>

**Comment by naticomstar** [comment]
לא הבנתי כלל.... :(

**Comment by shirachen** [comment]
כי נמחקו לניצו  מילים מהמייל שהם (seo) שלחו...
אין לי גישה למייל של דאטה פרו... אחפש ביום ד'  את המייל

**Comment by shirachen** [comment]
הנה ה שהם כתבו...
 הקוד של תג מנג׳ר באתר האופניים ממוקם כרגע אחרי תגית <head> , צריך להעביר אותו למיקום מיד אחרי תגית <body>

**Comment by shirachen** [comment]
יהה האנגלית לא נשלח 
אכתוב בעברית
הקוד כרגע ממוקדם אחרי תגית "האד" וצריך להעביר אותו אחרי תגית "בודי"

**Comment by shirachen** [comment]
איך לא חשבתי על זה קודם? 
![image](https://cloud.githubusercontent.com/assets/14195653/9897226/91a2f4a4-5c4e-11e5-8c0c-2526f3b55a0c.png)

**Comment by naticomstar** [comment]
עודכן מיקום טאג מנג'ר

**Comment by shirachen** [comment]
איך? לא אמרת לי לברר לך משהו?

**Comment by naticomstar** [comment]
שלחת לי מייל עם התוכן של גוגל טאג מנג'ר, משם הצלחתי להבין באיזה קוד ספציפי מדובר.

**Comment by shirachen** [comment]
סבבה
