### ISSUE TITLE
כרום גלקסי 4 של רעות 

### ISSUE THREAD

**Issue by shirachen** [nizanmalkit/bike#47]
![image](https://cloud.githubusercontent.com/assets/14195653/9791693/fb6d074e-57e4-11e5-8475-024cfa998e72.png)

![image](https://cloud.githubusercontent.com/assets/14195653/9791703/0a2e303c-57e5-11e5-8f25-309edd657ecd.png)

![image](https://cloud.githubusercontent.com/assets/14195653/9791713/1971399a-57e5-11e5-8245-aa2b92919dc1.png)

![image](https://cloud.githubusercontent.com/assets/14195653/9791722/28819768-57e5-11e5-8e9a-eb108e15b70e.png)

**Comment by naticomstar** [comment]
עודכן נא בדיקתכן החוזרת
