### ISSUE TITLE
האתר אינו נתמך...

### ISSUE THREAD

**Issue by shirachen** [nizanmalkit/bike#48]
רצינו זה יוריד את הכל טיפה למטה ולא יהיה ככה וידרוס את האתר 
![image](https://cloud.githubusercontent.com/assets/14195653/9808740/b93cad12-586a-11e5-84ea-0ba039e1a731.png)

תודה!

**Comment by naticomstar** [comment]
עודכן

**Comment by shirachen** [comment]
איזה יופי!
