### ISSUE TITLE
גלילה בכרום לפטופ - מבחשב שלי מהבית

### ISSUE THREAD

**Issue by shirachen** [nizanmalkit/bike#49]
אין לי אפשרות כלל לגלול למטה את התפריט מימין... הוא תקוע רק עד איפה שרואים. ומה שנגלל זה שאר העמוד מצד שמאל
![image](https://cloud.githubusercontent.com/assets/14195653/9809994/a5fe55ba-5875-11e5-9b4e-efbcc9625a0b.png)

**Comment by shirachen** [comment]
מממ אחרי שניקיתי קצת קאש...
ככה זה נראה: חסרים לי האייקונים העגולים ואין לי אפשרות לגלול אליהם
![image](https://cloud.githubusercontent.com/assets/14195653/9810116/b3c3ca76-5876-11e5-86c9-6fce072bbd7e.png)

**Comment by naticomstar** [comment]
עודכן
