### ISSUE TITLE
כולם יכולים למחוק תמונות? של כולם? 

### ISSUE THREAD

**Issue by shirachen** [nizanmalkit/bike#5]
בעיקרון כל מי שהעלה תמונה הוא והאדמין של האתר היחידים שיכול לערוך אותה/ למחוק אותה

**Comment by naticomstar** [comment]
תוקן. רק מי שהעלה את התמונה יכול למחוק אותה או לערוך אותה (מנהל יכול דרך מערכת הניהול לעשות את פעולותיו כרגיל)

**Comment by shirachen** [comment]
אחלה - תודה
