### ISSUE TITLE
עמוד תוצאות חיפוש מהכרום שלי בבית

### ISSUE THREAD

**Issue by shirachen** [nizanmalkit/bike#50]
לא נמצאו תומצאות עולה על המומלצים -
ויש את המסלול השמאלי שתמיד בורח למטה. כן אני על 100%
![image](https://cloud.githubusercontent.com/assets/14195653/9810218/989acfbe-5877-11e5-91e8-62925e20f134.png)

**Comment by naticomstar** [comment]
עודכן. בנוסף, בעת חיפוש מתקדם, הוסתר "מסלולים מומלצים" (הם כבר לא ממש מומלצים שרלוונטים)

**Comment by shirachen** [comment]
תודה
