### ISSUE TITLE
גלילה במחשב שלי מהבית ה[בכרום

### ISSUE THREAD

**Issue by shirachen** [nizanmalkit/bike#52]
אין לי אפשרות לראות את הפופ אפ הוא למטה מידי אז  רציתי לגלול וגם את זה הוא  לא נתן לי 
הוא גלל את העמוד מתחת (המושחר)
זה היה עמוד מסלול
![image](https://cloud.githubusercontent.com/assets/14195653/9810776/c580269c-587b-11e5-9f6f-6e895b50914c.png)

**Comment by nizanmalkit** [comment]
גם אצלי קיימת אותה בעיה
1366X768

**Comment by naticomstar** [comment]
עודכן
