### ISSUE TITLE
כתבות שטח - שיתוף

### ISSUE THREAD

**Issue by shirachen** [nizanmalkit/bike#53]
אין לי גישה לעיצובים 
צריך להיות כתוב משהו אחר... שתך את הכתבה/ מאמר...
![image](https://cloud.githubusercontent.com/assets/14195653/9832545/e220e5f0-5986-11e5-9bd9-66ce0112009f.png)

**Comment by naticomstar** [comment]
טכנית כתוב שם "שתף את המסלול"... אבל משנה לך ל"שתף את הכתבה"

![image](https://cloud.githubusercontent.com/assets/13998692/9835423/cd755480-59f2-11e5-9031-5f8115e01293.png)

**Comment by shirachen** [comment]
מהמם תודה
