### ISSUE TITLE
כתבות שטח "לכתבה המלאה" 

### ISSUE THREAD

**Issue by shirachen** [nizanmalkit/bike#54]
חסר לכולם לינק לכתבה המלאה...
![image](https://cloud.githubusercontent.com/assets/14195653/9832575/c5acfd2c-5987-11e5-94da-b00bacf75ed7.png)

**Comment by naticomstar** [comment]
ככה זה התקבל בעיצוב
![image](https://cloud.githubusercontent.com/assets/13998692/9835418/a14f14ea-59f2-11e5-836c-4bc082521daf.png)

**Comment by shirachen** [comment]
מה העלות לשנות?
