### ISSUE TITLE
אייקון בלשונית עליונה

### ISSUE THREAD

**Issue by shirachen** [nizanmalkit/bike#55]
היי האם אני יכולה שבלינקים של האופניים לא יהיה e 
וגם אין את זה בכל העמודים אלא רק בדף הבית - צריך שזה יהיה בכל העמודים.
 בכל מקרה אני רוצה לשים שם אייקון אחר, 
משהו שקשור לאתר האופניים
מה אני צריכה להעביר? jpg? באיזה מידה?
![image](https://cloud.githubusercontent.com/assets/14195653/9832606/d15d80d2-5988-11e5-8184-f84360c519bb.png)

**Comment by naticomstar** [comment]
בעיקרון זה כן בכל עמוד :)
אבל אם את רוצה אייקון אחר תעבירי קובץ בפורמט 
ico
בגודל
16X16

**Comment by shirachen** [comment]
בסדר אעביר ביום ד' 
תודה

**Comment by shirachen** [comment]
שולחת עכשוי במייל - עדכן כשבוצע 
תודה

**Comment by naticomstar** [comment]
עודכן
