### ISSUE TITLE
הרשמה מעמוד המלא

### ISSUE THREAD

**Issue by shirachen** [nizanmalkit/bike#57]
כשלוחצים "שלח" מההרשמה המלאה ולא ממלאים פרטים...
הטקסט "עליך לאשר את ההסכם" מופיע  פעמיים גם בהרשמה למטה.
![image](https://cloud.githubusercontent.com/assets/14195653/9832624/9e96d1a2-5989-11e5-9298-7eb255e2968f.png)

**Comment by naticomstar** [comment]
טופל
