### ISSUE TITLE
תיקונים מדפדפן של גלקסי 3

### ISSUE THREAD

**Issue by shirachen** [nizanmalkit/bike#58]
להלן המכשיר של הלקוחה...

דף הבית -  אם לוחצים על "הצג על גבי מפה" וגוללים למעלה, מפת גוגל עולה על החלק העליון של האתר
![image](https://cloud.githubusercontent.com/assets/14195653/9833011/85e4ceea-5991-11e5-9db3-bbd551c1eb13.png)

יש כפילות בהרשמה לניוזלטר:
בתחתית דף ההרשמה מתחת לתמונה יש שוב "הרשמה לניוזלטר".
אם אלחץ "שלח" כתוב יש לאשר ההסכם.

![image](https://cloud.githubusercontent.com/assets/14195653/9833020/b7c4e530-5991-11e5-95c7-fc031bab7ce4.png)

כשנכנסים לדף מסלול, מתחילה הורדה אוטומטית של מפת פי די אף של המסלול 
אם נכנסים לדף שוב, מוצגת הודעה ששואלת האם להוריד שוב את הקובץ.
כל הערב ירדו לי קבצי מסלול למובייל

![image](https://cloud.githubusercontent.com/assets/14195653/9833086/3f4a2d66-5993-11e5-9e78-ef8fb62590e1.png)

תמונות מעמוד מסלול 
כשעושים "חזור" מהגלריה, חוזרים לדף הבית ולא לדף מסלול
![image](https://cloud.githubusercontent.com/assets/14195653/9833357/8350775a-599c-11e5-86a5-667f4d22c5be.png)

 לאחר סגירת תמונה פס אפור בדף כוורת תמונות
![image](https://cloud.githubusercontent.com/assets/14195653/9833361/b2d4a064-599c-11e5-9f56-c3360ac9aff1.png)

אם משתפים במובייל במייל, אז הלינק נכנס לשורת הכתובת/נמען ולא לגוף ההודעה.
![image](https://cloud.githubusercontent.com/assets/14195653/9833369/d51ab262-599c-11e5-8522-8efd5998ce50.png)

כאשר נמצאים באחד מהטאבים בדף מסלול (מפות, גלריית תמונות וכו), ועושים "חזור" –
חוזרים לדף הבית ולא לדף מסלול.
בצילום לעייל צופים בסרטון ורוצים לחזור לאחור, חוזרים לדף הבית.
בכל הדפים כך.

![image](https://cloud.githubusercontent.com/assets/14195653/9833370/fe6897c4-599c-11e5-9f16-20f42245b4f8.png)

**Comment by naticomstar** [comment]
לוגו שעולה על השאר- תוקן כבר בעבר
"עליך לאשר את ההסכם" תוקן כבר בעבר
הורדת קובץ פי די אף תוקן ללחיצה על "מפות" בלבד במקום בעת טעינת דף. לא ניתן למנוע הורדת קובץ במובייל- כך הדפדפן בנוי.
פס אפור בצד- לא היה קשור לתמונה- סודר
תוקנה שליחת מייל אל דרך מובייל
האחרון לא תקלה. כיוון שהיא נמצאת באותו עמוד של המידע, לחיצה אחורה תביא אותה לדף הקודם שהיא היתה בו.
