### ISSUE TITLE
מומלץ לצפות בכרום ופיירפוקס גם מהמובייל

### ISSUE THREAD

**Issue by shirachen** [nizanmalkit/bike#59]
נרצה שהפופ אפ הזה יופיע בכל הדפדפנים הישנים/האחרים במובייל שלא תומכים באתר 
כפי שעשינו לאי ירוק

![image](https://cloud.githubusercontent.com/assets/14195653/9833383/480e14f8-599d-11e5-9963-7b0a026d7e7a.png)

**Comment by naticomstar** [comment]
תוספת

**Comment by shirachen** [comment]
קדימה, מה העלות?
וגם אני רוצה שהפופ אפ הזה באי ירוק (ובאופניים ברי הוא בתוך אי ירוק)  יהיה על כל העמודים שלו ולא רק בעמוד הבית....

**Comment by shirachen** [comment]
וגם, למה זה עולה עוד כסף? הרי זה יושב תחת ה
 url 
של אי ירוק
