### ISSUE TITLE
אקספלורר 11 לפטופ -  הרשמה בפוטר

### ISSUE THREAD

**Issue by shirachen** [nizanmalkit/bike#6]
בפוטר הכל קופץ ראה
![image](https://cloud.githubusercontent.com/assets/14195653/9757383/fc42df74-56e8-11e5-8ac2-6a7cc75e3ee1.png)

**Comment by naticomstar** [comment]
כעת תקין
![image](https://cloud.githubusercontent.com/assets/13998692/9762223/d9e604a2-570a-11e5-9a68-f37c5513e109.png)

**Comment by shirachen** [comment]
מממ לא תקין :(
![image](https://cloud.githubusercontent.com/assets/14195653/9784427/cfde2102-57b3-11e5-99bc-41d9613dd487.png)

**Comment by naticomstar** [comment]
אבקש לבדוק שוב, הצלחנו לסדר את זיהוי אקספלורר, וכעת אמור להיות תקין
