### ISSUE TITLE
הסרת תאריך הזנה מכתבות השטח

### ISSUE THREAD

**Issue by shirachen** [nizanmalkit/bike#60]
![image](https://cloud.githubusercontent.com/assets/14195653/9835390/86fb9cc2-59f1-11e5-84fa-482c79f6b27e.png)

שלא יופיע כלום...
תודה

**Comment by naticomstar** [comment]
חלק מהעיצוב, דורש שינוי

**Comment by shirachen** [comment]
מה העלות?
