### ISSUE TITLE
עמודי אב תחת קטגוריות איזורים

### ISSUE THREAD

**Issue by shirachen** [nizanmalkit/bike#61]
יש לנו עמודי אב - אבל כשלוחצים על קטגורית איזור כלשהו הם לא מוצגים

למשל עשיתי טסט על המסלול הזה...
![image](https://cloud.githubusercontent.com/assets/14195653/9835467/b3819c16-59f5-11e5-87d4-93662c1dd7da.png)

כשלוחצים על קטגוריית צפון הוא לא מופיע בתוצאות
![image](https://cloud.githubusercontent.com/assets/14195653/9835473/ed75488c-59f5-11e5-9056-02827fd02e38.png)

הוא צריך להופיע וגם "הילדים" שלו צריכים להופיע
תודה

**Comment by naticomstar** [comment]
עודכן
