### ISSUE TITLE
מסלולים מומלצים 

### ISSUE THREAD

**Issue by shirachen** [nizanmalkit/bike#62]
ראיתי שסידרת את אלו בעמוד הכללי של "הכול"
אבל התיקון הזה לא בוצע בעמודים האחרים 
צפון דרום ומרכז...
ראה 
![image](https://cloud.githubusercontent.com/assets/14195653/9835478/9f7ac7be-59f6-11e5-8578-80dfdac38b4f.png)

**Comment by shirachen** [comment]
וגם אם אנחנו כבר פה 
בתפריט מימין צריך להיות כתוב הכול עם ו
![image](https://cloud.githubusercontent.com/assets/14195653/9835481/cebd75b2-59f6-11e5-9e51-bcd68661436a.png)

**Comment by naticomstar** [comment]
עודכן + עודכן
