### ISSUE TITLE
מסלולים מומלצים - דרום ומרכז

### ISSUE THREAD

**Issue by shirachen** [nizanmalkit/bike#63]
היי נתי
כשהיה את התקלה עם המסלולים שתעברבבו בין המרכז לדרום 
זה לא נתן לאיילון להזין ממוצלים שם... הוא הזין במערכת וניסה שלמור - אבל זה לא  שמר לו
אנא בטיפולך 
שנוכל להזין גם שם מומלצים

![image](https://cloud.githubusercontent.com/assets/14195653/9835523/5e9010fe-59f8-11e5-8551-d514265dbb2e.png)
,

**Comment by naticomstar** [comment]
כעת תקין
