### ISSUE TITLE
החיפוש החופשי 

### ISSUE THREAD

**Issue by shirachen** [nizanmalkit/bike#64]
מה זה לא שואב מכל הטקסט את התוצאות?
למשל חיפוש של המילה 
עינב או האלה - לא מוצא את המסלול הזה
http://www.eyarok.org.il/bike/trip.aspx?id=1999

![image](https://cloud.githubusercontent.com/assets/14195653/9836159/4a37fb02-5a17-11e5-9430-d6793ca6d789.png)

![image](https://cloud.githubusercontent.com/assets/14195653/9836163/6dd7b728-5a17-11e5-9996-8f692cfde27e.png)

**Comment by naticomstar** [comment]
תוקן
