### ISSUE TITLE
לחיצה על צור קשר מהתפריט

### ISSUE THREAD

**Issue by shirachen** [nizanmalkit/bike#67]
זה לא מגיב לי...
אני מהמחשב שלי בבית והגימייל של פתוח

![image](https://cloud.githubusercontent.com/assets/14195653/9836252/80dff954-5a1a-11e5-8dbe-89e0cf27488d.png)

**Comment by naticomstar** [comment]
אנא נסי להיכנס לקישור הבא:
http://www.w3schools.com/tags/tryit.asp?filename=tryhtml_link_mailto
ולחצי על
 SendMail
 בצד ימין. אם לא עובד, הבעיה מגיעה מהדפדפן שלך וזה לא פתרון שאנו יכולים לפתור (יש בעיה שכיחה כזו בכרום בזמן האחרון)
