### ISSUE TITLE
הערות מיכל seo

### ISSUE THREAD

**Issue by shirachen** [nizanmalkit/bike#68]
בדף מסלולים בצפון
צריך שהכותרת "מסלולים בצפון" תהיה H1 ושלא יהיו H1 נוספות.

**Comment by shirachen** [comment]
הנה ככה זה לא מתהפך!
![image](https://cloud.githubusercontent.com/assets/14195653/9897389/37097a3e-5c50-11e5-9ed2-8fb332150e86.png)

**Comment by naticomstar** [comment]
עודכן קוד. האם תקין כעת?

**Comment by shirachen** [comment]
ראו מה מיכל ענתנ לי
בדף של מסלולים בצפון כן.
אבל הם תיקנו את זה רק שם.
זה צריך להיות גם בדרום, מרכז והכול כמובן.

**Comment by naticomstar** [comment]
שתנקה קאש בבקשה, צפון דרום ומרכז הינם עמודים דינאמים שמקבלים את אותן הפקודות

**Comment by shirachen** [comment]
ראה תשובתה
לא :-(
תסתכלו בקוד.
כאן http://www.eyarok.org.il/bike/trips.aspx?filter=center
H1 זה תצוגה על גבי מפה ולא מסלולים במרכז

**Comment by naticomstar** [comment]
עכשיו עודכן תקין.
