### ISSUE TITLE
הערות של מיכל

### ISSUE THREAD

**Issue by shirachen** [nizanmalkit/bike#69]
![image](https://cloud.githubusercontent.com/assets/14195653/9897396/5cf300f8-5c50-11e5-8ad1-b5a3b7df55ce.png)

אלו הלינקים 
http://www.eyarok.org.il/bike/maintrip.aspx?id=1

וזה צילום מסך
![image](https://cloud.githubusercontent.com/assets/14195653/9897408/a65a787a-5c50-11e5-8ef4-b1e3ef0aa5e4.png)

**Comment by shirachen** [comment]
הנה עוד דוגמה ומייל שקיבלתי בנושא
![image](https://cloud.githubusercontent.com/assets/14195653/9897876/341152a6-5c56-11e5-8aae-9bcb2f6a7190.png)

**Comment by naticomstar** [comment]
עודכן + עודכן
