### ISSUE TITLE
עוד הערות של מיכל

### ISSUE THREAD

**Issue by shirachen** [nizanmalkit/bike#70]
![image](https://cloud.githubusercontent.com/assets/14195653/9897838/d2feddf8-5c55-11e5-880a-c8ba8ce3c874.png)

**Comment by naticomstar** [comment]
כותרת משנה ניתנת לעריכה, כמו תמיד:
![image](https://cloud.githubusercontent.com/assets/13998692/9901168/59edd432-5c6e-11e5-8832-707031dad1bc.png)

סעיף 2 דורש שינוי- חצי שעת עבודה- יש לקחת בחשבון שהדבר משפיע גם על אתר אי ירוק

סעיף 3- קיים
![image](https://cloud.githubusercontent.com/assets/13998692/9901273/2cee7616-5c6f-11e5-9193-72ba7687a03d.png)

**Comment by shirachen** [comment]
לא הבנתי
סעיף 2 שלה בוצע? 
וסעיף 3 זה זה שקשור לעלות?

**Comment by naticomstar** [comment]
תת כותרת תמיד היתה ניתנת לעריכה- תקין
סעיף 2 דורש שינוי, לא בוצע עד שתאשרו חצי שעת עבודה
סעיף 3 קיים כבר- תקין

**Comment by shirachen** [comment]
לא הבנתי למה זה עולה כסף?

**Comment by naticomstar** [comment]
כיוון שלא הוגדר באיפיון

**Comment by shirachen** [comment]
מאושר חצי שעה -
מוסיפה למייל המאושרים שלנו - לא לשלוח שם מחזור

**Comment by naticomstar** [comment]
בוצע

**Comment by shirachen** [comment]
מהרס

**Comment by shirachen** [comment]
עוד שאלה 
האם כותרות הטאבים מוגדרות כ h2 
??
הכוונה לאלו
![image](https://cloud.githubusercontent.com/assets/14195653/9925800/21cd72d8-5d18-11e5-9a98-84b8697150de.png)

גם בכתבות השטח.... 
![image](https://cloud.githubusercontent.com/assets/14195653/9925815/5aa408ba-5d18-11e5-9b49-8596138c6cdf.png)

**Comment by naticomstar** [comment]
כן. שימי לב שאת לא באותו מסלול. הכותרות בעמוד שהלקוחות רואים וצילמת שייך לתוכן הראשי והם לא טאבים

![image](https://cloud.githubusercontent.com/assets/13998692/9927552/3528ae6e-5d28-11e5-83f4-ecb8e57f3540.png)

![image](https://cloud.githubusercontent.com/assets/13998692/9927557/3c28e512-5d28-11e5-854a-bf87f7b10e67.png)
