### ISSUE TITLE
כרום נייד סמסונג 3

### ISSUE THREAD

**Issue by shirachen** [nizanmalkit/bike#72]
![image](https://cloud.githubusercontent.com/assets/14195653/9898685/074309b6-5c5d-11e5-9cd2-771569fd21bf.png)

![image](https://cloud.githubusercontent.com/assets/14195653/9898689/17c81e70-5c5d-11e5-981a-d9faae429e2a.png)

![image](https://cloud.githubusercontent.com/assets/14195653/9898700/264cdefe-5c5d-11e5-9fc5-c6a6869aa66f.png)

**Comment by naticomstar** [comment]
תבדקו שוב בבקשה. עברנו על הסוגיות האלה כבר לפני כמה ימים וזה כבר טופל.
