### ISSUE TITLE
באנר באתר 

### ISSUE THREAD

**Issue by shirachen** [nizanmalkit/bike#73]
אלכס הטמיע את הבאנר באתר - אך עדיין מצא שם תקלה.
הוא מבקש שתתקשר אליו. 
תודה

**Comment by naticomstar** [comment]
דיברתי עם אלכס ועכשיו עובד תקין

**Comment by shirachen** [comment]
?זה תקין
![image](https://cloud.githubusercontent.com/assets/14195653/9902616/8f724ce6-5c78-11e5-9f0d-e9c27b43bebd.png)

**Comment by naticomstar** [comment]
אמממ... כן.....
