### ISSUE TITLE
הורדת קובצי ניווט באקספלורר 10 

### ISSUE THREAD

**Issue by shirachen** [nizanmalkit/bike#76]
איטי מאוד ולא מוריד :( 
![image](https://cloud.githubusercontent.com/assets/14195653/9900827/1806172a-5c6c-11e5-8117-e6dc91fff0f4.png)

**Comment by shirachen** [comment]
גם בכרום... 
![image](https://cloud.githubusercontent.com/assets/14195653/9901073/c4150ebc-5c6d-11e5-868f-1483feedda0a.png)

**Comment by naticomstar** [comment]
לא תלוי בקוד אלא ברמת שרת...
