### ISSUE TITLE
פירורי לחם

### ISSUE THREAD

**Issue by shirachen** [nizanmalkit/bike#78]
צריך להיות כאן

דף הבית - כתבות שטח - שם הכתבה...
![image](https://cloud.githubusercontent.com/assets/14195653/9901979/c44fe2de-5c73-11e5-815a-80eab9524574.png)

**Comment by naticomstar** [comment]
נוסף (למרות שלא דובר באיפיון)

**Comment by shirachen** [comment]
תודה חיים של...

**Comment by shirachen** [comment]
רגע אבל אני לא רואה את זה בעמוד אירוע....

**Comment by naticomstar** [comment]
דיברנו על זה כבר בריג'קט אחר

**Comment by shirachen** [comment]
אכן צודק
