### ISSUE TITLE
לינקים פוטר מובייל 

### ISSUE THREAD

**Issue by shirachen** [nizanmalkit/bike#79]
שהסדר יהיה זהה לזה של הדסקטופ 

זה בניהול? 
זה הסדר שאנחנו רוצים - צריך שזה יהיה ככה גם במובייל
![image](https://cloud.githubusercontent.com/assets/14195653/9902020/0e7bd264-5c74-11e5-9234-2ed94ac06828.png)

**Comment by naticomstar** [comment]
שימו לב שהסדר הוא מימין לשמאל ולא מלמעלה למטה, לכן הסדר שלכם "שונה"

**Comment by shirachen** [comment]
לא הבנתי... :(

**Comment by naticomstar** [comment]
הסדר של הלינקים הנכון הוא:
![image](https://cloud.githubusercontent.com/assets/13998692/9902714/46615e56-5c79-11e5-8752-24e3e0c08e06.png)

**Comment by shirachen** [comment]
אתמול אני זוכרת שראיתי את זה תקין...
היום זה לא ככה.

**Comment by naticomstar** [comment]
תקין. מזכיר שבשביל לראות שינוי את צריכה לרענן את הדף

**Comment by shirachen** [comment]
זה לא עובד באייפון 
וגם לא באנדוראיד של הלקוחה...

**Comment by shirachen** [comment]
זה צילום מסך מהאייפון שלי
![image](https://cloud.githubusercontent.com/assets/14195653/9927617/db1824f8-5d28-11e5-80da-52e70be6fbc4.png)

**Comment by naticomstar** [comment]
וזה צילום מסך ממסך מחשב. הסדר אותו סדר
![image](https://cloud.githubusercontent.com/assets/13998692/9928228/809ad61a-5d2d-11e5-9235-3e175c72d900.png)
