### ISSUE TITLE
חיפוש מתקדם באקספלורר 11 לפטופ

### ISSUE THREAD

**Issue by shirachen** [nizanmalkit/bike#8]
![image](https://cloud.githubusercontent.com/assets/14195653/9757445/4abef0d4-56e9-11e5-9099-16004ceebcf7.png)

**Comment by shirachen** [comment]
ככה זה נראה בלפטופ באקסלורר 10
![image](https://cloud.githubusercontent.com/assets/14195653/9757704/cbcc98b0-56ea-11e5-91b8-a0c7edc5ac93.png)

**Comment by naticomstar** [comment]
עודכן חיפוש באקספלורר, כעת אמור להיראות ולהתנהג תקין

**Comment by shirachen** [comment]
זה עדיין לא תקין אצלי אחרי ניקוי קאש...
ולא בדקתי בכלל באקספלורר 10 
![image](https://cloud.githubusercontent.com/assets/14195653/9783978/f3c4af3a-57b0-11e5-9b52-2e609aa53193.png)

**Comment by naticomstar** [comment]
עודכן

**Comment by shirachen** [comment]
נתיי 
חרי ניקוי קאש וכו מהכרום בלפטופ שלי...
![image](https://cloud.githubusercontent.com/assets/14195653/9811009/50f32426-587d-11e5-930f-4c86076b66aa.png)

**Comment by shirachen** [comment]
תתעלם = עכשיו זה בסדר!
