### ISSUE TITLE
שאריות תיוקנים מהאייפון

### ISSUE THREAD

**Issue by shirachen** [nizanmalkit/bike#80]
היי נתי,
מזכירה לך שנאשר לנו לטפל בנושא ההתחברות האייפון 
ובנושא כפתור השיתוף מכתבות השטח

תודה!!

**Comment by naticomstar** [comment]
אנא נסי כעת: 1. להתחבר מההייפון
2. ללחוץ על "שתף" בכתבות מגזין

**Comment by shirachen** [comment]
שתף - לא עובד
הפתור כלל לא מגיב

ההתחברות - עובד!

**Comment by naticomstar** [comment]
ועכשיו?

**Comment by shirachen** [comment]
לא :(

**Comment by naticomstar** [comment]
ועכשיו
