### ISSUE TITLE
תשובתיי בנוגע לפירורים

### ISSUE THREAD

**Issue by shirachen** [nizanmalkit/bike#81]
שוחחתי עם מיכל...
היא אומר השעיף שיהיה עוד פירור כאן
כפי שעשינו בכתבות השטח

בבקשה הוסיף פירור "אירועים" 
![image](https://cloud.githubusercontent.com/assets/14195653/9926605/b147aa76-5d1f-11e5-8870-28e7632c9080.png)

תודה

**Comment by naticomstar** [comment]
בוצע

**Comment by shirachen** [comment]
תודה!
