### ISSUE TITLE
רשימת מסלולים מלאה - אייפון

### ISSUE THREAD

**Issue by shirachen** [nizanmalkit/bike#83]
רשימת המסלולים המלאה באייפון נחתכת שןרה 

![image](https://cloud.githubusercontent.com/assets/14195653/9927369/bd672f0a-5d26-11e5-9bdc-95eaa310d1e8.png)

**Comment by naticomstar** [comment]
הוקטן

**Comment by shirachen** [comment]
זה עדיין נחתך... לא צריך להקטין אלא לתת לכותרת שתי שורות ולא שורה אחת

**Comment by naticomstar** [comment]
עודכן

**Comment by shirachen** [comment]
להיט
