### ISSUE TITLE
טעיות שגורות בחיפוש

### ISSUE THREAD

**Issue by shirachen** [nizanmalkit/bike#84]
היי ,
איפה זה קיים במערכת בעמודי מסלול וכו?

ראה שורה 77 באקסל 
![image](https://cloud.githubusercontent.com/assets/14195653/9927408/0987ede8-5d27-11e5-977e-6a1d0a24b6e1.png)

**Comment by naticomstar** [comment]
![Uploading image.png…]()

**Comment by shirachen** [comment]
אני לא רואה כלום.

**Comment by naticomstar** [comment]
![image](https://cloud.githubusercontent.com/assets/13998692/9928203/57d6d9b8-5d2d-11e5-86a5-b27ab4a132a1.png)
(זה כבר הוסבר בעבר, נשלחו מיילים)

**Comment by shirachen** [comment]
את זה ראיתי.
לא ראיתי לכל עמוד מסלול ספציפי...

**Comment by naticomstar** [comment]
זה לא לפי עמוד ספציפי. כל מילה אשר נכתבת לא נכון בחיפוש אמורה להיות מתוקנת

**Comment by shirachen** [comment]
היי נתי הבנתי 
עשינו טקטס אך זה לא עבד 
ראה צילומי מסך
זה מה שהזנו בניהול
![image](https://cloud.githubusercontent.com/assets/14195653/9929601/8165902c-5d36-11e5-9fd0-148f124569e8.png)

וככה זה נראה באתר 
![image](https://cloud.githubusercontent.com/assets/14195653/9929589/6e4bb8a4-5d36-11e5-9963-902c8d620d32.png)

**Comment by naticomstar** [comment]
שלחנו לכם בזמנו איך עובדים עם אזור זה. שלחתי לך את זה כרגע שוב

**Comment by shirachen** [comment]
לאן למייל?

**Comment by shirachen** [comment]
היי נתי,
תראה שוב מה הזנו בניהול
ועשינו איפוס רשומות סטטיות...
![image](https://cloud.githubusercontent.com/assets/14195653/9930968/2cfb3410-5d40-11e5-8079-6e4357e906fd.png)

ומה זה נותן בתוצאות החיפוש
ועשיתי ניקוי קאש
![image](https://cloud.githubusercontent.com/assets/14195653/9930985/47c186fa-5d40-11e5-9932-f5aa944a9aa5.png)

**Comment by naticomstar** [comment]
כעת תקין

**Comment by shirachen** [comment]
כעת תקין.
תודה
