### ISSUE TITLE
 במובייל - כפתור ההרשמה לניוזלטר

### ISSUE THREAD

**Issue by shirachen** [nizanmalkit/bike#85]
היי נתי הכפתור השחור - זה 
![image](https://cloud.githubusercontent.com/assets/14195653/9932975/9ebe5dba-5d50-11e5-9b61-4d8cb24b08e2.png)

לא צריך להיות במובייל בעמוד ההרשמה ובעמוד ותודה שנרשמת.

תודה

**Comment by naticomstar** [comment]
עודכן
