### ISSUE TITLE
תצוגה על גבי מפה מדף הבית במובייל

### ISSUE THREAD

**Issue by shirachen** [nizanmalkit/bike#88]
באתר במובייל יש שני חיצים -על גבי המפה שגורמים למפה "להיתדפדף" חחח 
וגללים את הגולש למסלולים האחרים
מכיוון שהכל קטן קשה "לשחק" עם המפה...
אז חשבתי אולי אם נעלה את שני החיצים למעלה - זה יקל על הבעיה
ראה כוונתי
![image](https://cloud.githubusercontent.com/assets/14195653/9979745/7d3f864c-5f84-11e5-8d16-8e41d5bc9535.png)

מה דעתך?

**Comment by naticomstar** [comment]
דיברנו, עודכן
