### ISSUE TITLE
עמוד אירועים - מסכי לפטופ אקספלורר 11

### ISSUE THREAD

**Issue by shirachen** [nizanmalkit/bike#9]
![image](https://cloud.githubusercontent.com/assets/14195653/9757460/6b0e5d5c-56e9-11e5-8458-4cef53b19714.png)

**Comment by naticomstar** [comment]
תוקן כבר אתמול

**Comment by shirachen** [comment]
במסך שלי לפטופ זה לא עובד...

**Comment by naticomstar** [comment]
עודכן
