### ISSUE TITLE
מפות

### ISSUE THREAD

**Issue by shirachen** [nizanmalkit/bike#90]
הלקוחה אומרת שהמפת pdf
יורדת לה לנייד ולא שואלת לפני..
וכבר עשינו את התיקון הזה הרי.
הייתכן?

**Comment by naticomstar** [comment]
שתנקה קאש בבקשה. הדבר תקין.

**Comment by shirachen** [comment]
גם אצל איילון ואילנה ככה זה מופיע 
ראה מה כתב לי איילון מהאנדרואיד שלו

"לגבי המפות, זה לא מוריד אוטמטית אבל גם לא מעלה הודעת בחירה"

**Comment by shirachen** [comment]
הכי חשוב שזה לא ירד אוטומית למכשיר... היא עשתה 
בדיקה מהמכשיר של הבן שלה ואצלו זה ירד למכשיר ישר

**Comment by naticomstar** [comment]
כשאת אומרת שזה ירד למכשיר, הכוונה שהיא לחצה על הלינק ואז זה ירד למכשיר?או שנכנסה לעמוד וזה ירד למכשיר (וכשאני אומר "נכנסה לעמוד אני מתכוון העמוד עלה, או לחצה על "מפות" בלבד)

**Comment by shirachen** [comment]
ראה תשובתה
נכנסתי לדף מסלול-מפות- מפת PDF – לחצתי על זה ומייד החלה הורדת המפה
