### ISSUE TITLE
גלריית תמונות במובייל

### ISSUE THREAD

**Issue by shirachen** [nizanmalkit/bike#91]
גלריית תמונות במובייל.
כשפותחים את התמונה הראשונה לא מופיע עליה חץ לדפדוף 
ככה שמי שלא לוחץ עליה פעם אחת לא יודע שיש  חיצי דפדוף
וגם כאשר הם כבר עולים הם ענקיים..
ראה באייפון שלי
![image](https://cloud.githubusercontent.com/assets/14195653/10067331/50a184c8-62a4-11e5-853a-2f4e796bd234.png)

**Comment by naticomstar** [comment]
עודכן

**Comment by shirachen** [comment]
אי אפשר להיכנס לעמוד מסלול עכשיו.. זה מעלה הודעת שגיאה..
שלחתי לך תמונה בווטאס
