### ISSUE TITLE
מחיקת תמונות גולשים מהניהול

### ISSUE THREAD

**Issue by shirachen** [nizanmalkit/bike#92]
היי נתוש,
איילון עדיין לא מצליח למחוק תמונות גולשים דרך הניהול 
למשל את התמונה הזה שתקועה לנו  בחדיד 
http://www.eyarok.org.il/bike/trip.aspx?id=1961

![image](https://cloud.githubusercontent.com/assets/14195653/10067586/7759e5ae-62a6-11e5-8dda-277bde7b9d7e.png)

**Comment by naticomstar** [comment]
עודכן. ניתן כעת למחוק תמונות ע"י אדמין
