### ISSUE TITLE
הפניות לא ברורות שעליתי עליהן באנליטיקס

### ISSUE THREAD

**Issue by shirachen** [nizanmalkit/bike#96]
ראה מה שלחתי למיכל יועצת ה seo
![image](https://cloud.githubusercontent.com/assets/14195653/10451749/c1137d46-71aa-11e5-992f-714c44f9d4a1.png)
זה קורה בעוד עמודים למשל:
![image](https://cloud.githubusercontent.com/assets/14195653/10451780/f407aaba-71aa-11e5-8c77-2c61ec246f86.png)

וראה תשובתה
למה יש הפניה מ
http://www.eyarok.org.il/bike/bike/trip.aspx?id=1998
ל:
http://www.eyarok.org.il/bike/page.aspx?id=201
מה הקשר?
זה באג באתר שלנו שצריך לפתור מול הפיתוח.

 תודה שירה אנא בדיקתך

**Comment by OmerComstar** [comment]
הי שירה.
אני לא יודע מדוע האנליטיקס מפנה לעמודים הללו, אך אלו לא עמודים שקיימים ונראה שזה טעות של האנליטיקס עצמו.
העמוד אליו האנליטיקס מפנה הוא:
http://www.eyarok.org.il/bike/bike/trip.aspx?id=1998
בזמן שהקישור האמיתי אמור להיות:
http://www.eyarok.org.il/bike/trip.aspx?id=1998

עמוד זה תקין ועובד, והוא גם מה שהאנליטיקס סופר (כי אחרת לא היו נתונים באנליטיקס).

**Comment by shirachen** [comment]
ראה תשובתה של מיכל
אני אסביר.
צריך לשאול אותו ישירות (בלי קשר לאנליטיקס)
למה כשפונים לכתובת שגויה כמו זו למשל
http://www.eyarok.org.il/bike/bike/trip.aspx?id=1998
מנותבים לדף לגמרי אחר ולא ל 404.

**Comment by naticomstar** [comment]
הפניות 404 כעת עובדות (יעלו לאחר הפגישה)
