### ISSUE TITLE
לינק נוסף בסוף עמוד מסלול

### ISSUE THREAD

**Issue by shirachen** [nizanmalkit/bike#97]
![image](https://cloud.githubusercontent.com/assets/14195653/10456549/a38709ee-71ca-11e5-9662-4e6aacedb753.png)

**Comment by OmerComstar** [comment]
הקישורים נוספו בתוך עמוד עריכת מסלול, תחת הטאב: "דברים נוספים לאופניים"

**Comment by shirachen** [comment]
תודה רבה
